FROM debian:buster

ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN true

# install build dependencies, then clean up system packages
RUN apt-get update && apt-get -y install \
    make \
    zlib1g-dev \
    libssl-dev \
    gperf \
    cmake \
    clang \
    libc++-dev \
    libc++abi-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /build

code:
    GIT CLONE https://github.com/pylakey/td /code

build:
    FROM +code
    ARG TARGETARCH

    RUN CXXFLAGS="-stdlib=libc++" \
        CC=/usr/bin/clang \
        CXX=/usr/bin/clang++ \
        cmake \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX:PATH=/tdlib \
        -S /code \
        -B /build

    RUN cmake --build /build --target install

    SAVE ARTIFACT /tdlib/lib/libtdjson.so.1.7.6 AS LOCAL ../aiotdlib/tdlib/linux/${TARGETARCH}/libtdjson.so
